import os

# Write findings.py using line-by-line approach
lines = []
lines.append('from __future__ import annotations')
lines.append('')
lines.append('import json')
lines.append('import sqlite3')
lines.append('from datetime import datetime')
lines.append('from pathlib import Path')
lines.append('from typing import Any, Dict, List, Optional')
lines.append('')
lines.append('from .models import Finding, Severity')
lines.append('')
lines.append('')
lines.append('class FindingStore:')
lines.append('    def __init__(self, db_path: str = "findings.db"):')
lines.append('        self.db_path = Path(db_path)')
lines.append('        self._init_db()')
lines.append('')
lines.append('    def _init_db(self):')
lines.append('        with sqlite3.connect(self.db_path) as conn:')
lines.append('            conn.execute("""')
lines.append('                CREATE TABLE IF NOT EXISTS findings (')
lines.append('                    id TEXT PRIMARY KEY,')
lines.append('                    campaign_id TEXT NOT NULL,')
lines.append('                    step_id TEXT NOT NULL,')
lines.append('                    tool TEXT NOT NULL,')
lines.append('                    vuln_type TEXT NOT NULL,')
lines.append('                    title TEXT NOT NULL,')
lines.append('                    description TEXT,')
lines.append('                    host TEXT,')
lines.append('                    port INTEGER,')
lines.append('                    parameter TEXT,')
lines.append('                    evidence TEXT,')
lines.append('                    cvss_vector TEXT,')
lines.append('                    cvss_score REAL,')
lines.append('                    severity TEXT,')
lines.append('                    cve_ids TEXT,')
lines.append('                    references TEXT,')
lines.append('                    tags TEXT,')
lines.append('                    status TEXT DEFAULT "open",')
lines.append('                    dedup_hash TEXT NOT NULL,')
lines.append('                    created_at TEXT NOT NULL,')
lines.append('                    updated_at TEXT NOT NULL')
lines.append('                )')
lines.append('            """)')
lines.append('            conn.execute("CREATE INDEX IF NOT EXISTS idx_campaign ON findings(campaign_id)")')
lines.append('            conn.execute("CREATE INDEX IF NOT EXISTS idx_dedup ON findings(dedup_hash)")')
lines.append('            conn.execute("CREATE INDEX IF NOT EXISTS idx_host ON findings(host)")')
lines.append('            conn.execute("CREATE INDEX IF NOT EXISTS idx_severity ON findings(severity)")')
lines.append('            conn.commit()')
lines.append('')
lines.append('    def add(self, finding: Finding) -> bool:')
lines.append('        finding.compute_dedup_hash()')
lines.append('')
lines.append('        with sqlite3.connect(self.db_path) as conn:')
lines.append('            cursor = conn.execute(')
lines.append('                "SELECT id FROM findings WHERE dedup_hash = ?",')
lines.append('                (finding.dedup_hash,)')
lines.append('            )')
lines.append('            existing = cursor.fetchone()')
lines.append('')
lines.append('            if existing:')
lines.append('                conn.execute("""')
lines.append('                    UPDATE findings SET')
lines.append('                        evidence = json_merge(evidence, ?),')
lines.append('                        updated_at = ?,')
lines.append('                        status = ?')
lines.append('                    WHERE dedup_hash = ?')
lines.append('                """, (json.dumps(finding.evidence), datetime.utcnow().isoformat(), finding.status, finding.dedup_hash))')
lines.append('            else:')
lines.append('                conn.execute("""')
lines.append('                    INSERT INTO findings (')
lines.append('                        id, campaign_id, step_id, tool, vuln_type, title, description,')
lines.append('                        host, port, parameter, evidence, cvss_vector, cvss_score, severity,')
lines.append('                        cve_ids, references, tags, status, dedup_hash, created_at, updated_at')
lines.append('                    ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)')
lines.append('                """, (')
lines.append('                    finding.id,')
lines.append('                    finding.campaign_id,')
lines.append('                    finding.step_id,')
lines.append('                    finding.tool,')
lines.append('                    finding.vuln_type,')
lines.append('                    finding.title,')
lines.append('                    finding.description,')
lines.append('                    finding.host,')
lines.append('                    finding.port,')
lines.append('                    finding.parameter,')
lines.append('                    json.dumps(finding.evidence),')
lines.append('                    finding.cvss_vector,')
lines.append('                    finding.cvss_score,')
lines.append('                    finding.severity.value,')
lines.append('                    json.dumps(finding.cve_ids),')
lines.append('                    json.dumps(finding.references),')
lines.append('                    json.dumps(finding.tags),')
lines.append('                    finding.status,')
lines.append('                    finding.dedup_hash,')
lines.append('                    finding.created_at,')
lines.append('                    finding.updated_at,')
lines.append('                ))')
lines.append('            conn.commit()')
lines.append('        return True')

with open('C:/temp/omniscience-cyber/rag/findings.py', 'w') as f:
    f.write('\n'.join(lines))

print("Part 1 done")