# Part 2B: Command methods
import os

lines = []
lines.append('    def do_run(self, arg: str):')
lines.append('    """run <target> [template] - Create and run a new campaign."""')
lines.append('    args = shlex.split(arg)')
lines.append('    if not args:')
lines.append('        print("Usage: run <target> [template]")')
lines.append('        return')
lines.append('')
lines.append('    target = args[0]')
lines.append('    template = args[1] if len(args) > 1 else "web_recon"')
lines.append('')
lines.append('    print(f"[+] Creating campaign for {target} using template \'{template}\'...")')
lines.append('    campaign = self._create_campaign(target, template)')
lines.append('')
lines.append('    if self.dry_run:')
lines.append('        print(f"[DRY RUN] Campaign {campaign.id} created (not executed)")')
lines.append('        self._show_campaign_plan(campaign)')
lines.append('        return')
lines.append('')
lines.append('    print(f"[+] Campaign {campaign.id} created. Starting execution...")')
lines.append('    self._run_campaign(campaign)')
lines.append('')
lines.append('    def do_plan(self, arg: str):')
lines.append('    """plan <target> [template] - Create campaign plan without executing."""')
lines.append('    args = shlex.split(arg)')
lines.append('    if not args:')
lines.append('        print("Usage: plan <target> [template]")')
lines.append('        return')
lines.append('')
lines.append('    target = args[0]')
lines.append('    template = args[1] if len(args) > 1 else "web_recon"')
lines.append('')
lines.append('    campaign = self._create_campaign(target, template)')
lines.append('    print(f"[+] Campaign {campaign.id} created (planned only)")')
lines.append('    self._show_campaign_plan(campaign)')
lines.append('')
lines.append('    def _create_campaign(self, target: str, template: str) -> Campaign:')
lines.append('    from .planner import create_campaign_from_template')
lines.append('    campaign = create_campaign_from_template(template, target)')
lines.append('    self.store.save(campaign)')
lines.append('    return campaign')
lines.append('')
lines.append('    def _show_campaign_plan(self, campaign: Campaign):')
lines.append('    print(f"\\nCampaign: {campaign.name} ({campaign.id})")')
lines.append('    print(f"Target: {campaign.target}")')
lines.append('    print(f"Template: {campaign.metadata.get(\'template\', \'unknown\')}")')
lines.append('    print(f"Steps ({len(campaign.steps)}):")')
lines.append('    for i, step in enumerate(campaign.steps, 1):')
lines.append('        deps = f" (depends on: {\', \'.join(step.depends_on)})" if step.depends_on else ""')
lines.append('        cond = f" [condition: {step.condition}]" if step.condition else ""')
lines.append('        print(f"  {i}. {step.id} [{step.tool}]{deps}{cond}")')
lines.append('        print(f"     {step.description}")')
lines.append('        print(f"     Args: {\' \'.join(step.args)}")')
lines.append('    print()')
lines.append('')

with open('C:/temp/omniscience-cyber/rag/shell.py', 'a', encoding='utf-8') as f:
    f.write('\n'.join(lines))

print('Part 2B written')