import os

# Part 2A: OmniscienceShell class - class definition and init
lines = []
lines.append('class OmniscienceShell(cmd.Cmd):')
lines.append('    """Interactive REPL for omniscience-cyber."""')
lines.append('')
lines.append('    intro = textwrap.dedent("""')
lines.append('        Commands:')
lines.append('          run <target> [template]     - Create and run a new campaign')
lines.append('          plan <target> [template]    - Create campaign plan without executing')
lines.append('          list                        - List all campaigns')
lines.append('          show <campaign_id>          - Show campaign details')
lines.append('          findings <campaign_id>      - Show campaign findings')
lines.append('          export <campaign_id> [fmt]  - Export report (md/html/json)')
lines.append('          step <campaign_id>          - Execute next step(s) in campaign')
lines.append('          pause <campaign_id>         - Pause running campaign')
lines.append('          resume <campaign_id>        - Resume paused campaign')
lines.append('          inject <campaign_id> <step> - Inject custom step into campaign')
lines.append('          audit <campaign_id>         - Show audit trail for campaign')
lines.append('          help                        - Show this help')
lines.append('          exit / quit                 - Exit shell')
lines.append('')
lines.append('        Templates: web_recon, infra_recon, ad_enum, mobile_recon')
lines.append('')
lines.append('        Step-by-step mode: Use \'step\' to execute one step at a time,')
lines.append('        then inspect findings before continuing with \'resume\' or \'step\'.')
lines.append('    """)')
lines.append('')
lines.append('    prompt = "omni> "')
lines.append('')
lines.append('    def __init__(self, config: dict = None, dry_run: bool = False):')
lines.append('        super().__init__()')
lines.append('        self.config = config or {}')
lines.append('        self.dry_run = dry_run')
lines.append('')
lines.append('        # Initialize components')
lines.append('        self.store = CampaignStateStore("campaigns")')
lines.append('        self.finding_store = create_finding_store("findings.db")')
lines.append('        self.executor = KaliExecutor(ExecutorConfig())')
lines.append('')
lines.append('        # Load scope guard from config')
lines.append('        guard_config = self.config.get("guardrails", {})')
lines.append('        self.scope_guard = ScopeGuard(')
lines.append('            in_scope_hosts=guard_config.get("in_scope_hosts", []),')
lines.append('            forbid=guard_config.get("forbid", []),')
lines.append('            block_out_of_scope=bool(guard_config.get("forbid", [])),')
lines.append('        )')
lines.append('        self.executor.set_scope_guard(self.scope_guard)')
lines.append('')
lines.append('        # Tab completion')
lines.append('        self._campaign_cache = []')
lines.append('        self._update_campaign_cache()')
lines.append('')
lines.append('    def _update_campaign_cache(self):')
lines.append('        """Update campaign ID cache for tab completion."""')
lines.append('        campaigns = self.store.list()')
lines.append('        self._campaign_cache = [c["id"] for c in campaigns]')
lines.append('')
lines.append('    def complete_show(self, text, line, begidx, endidx):')
lines.append('        return [c for c in self._campaign_cache if c.startswith(text)]')
lines.append('')
lines.append('    complete_findings = complete_show')
lines.append('    complete_export = complete_show')
lines.append('    complete_step = complete_show')
lines.append('    complete_pause = complete_show')
lines.append('    complete_resume = complete_show')
lines.append('    complete_audit = complete_show')
lines.append('')
lines.append('    def complete_run(self, text, line, begidx, endidx):')
lines.append('        parts = shlex.split(line)')
lines.append('        if len(parts) == 2:')
lines.append('            return [t for t in ["web_recon", "infra_recon", "ad_enum", "mobile_recon"] if t.startswith(text)]')
lines.append('        return [c for c in self._campaign_cache if c.startswith(text)]')
lines.append('')
lines.append('    complete_plan = complete_run')
lines.append('')

with open('C:/temp/omniscience-cyber/rag/shell.py', 'a', encoding='utf-8') as f:
    f.write('\n'.join(lines))

print('Part 2A written')